/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/liyanyanli/k8s-controller-custom-resource/pkg/apis/democrd/v1"
	scheme "github.com/liyanyanli/k8s-controller-custom-resource/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DemocrdsGetter has a method to return a DemocrdInterface.
// A group's client should implement this interface.
type DemocrdsGetter interface {
	Democrds(namespace string) DemocrdInterface
}

// DemocrdInterface has methods to work with Democrd resources.
type DemocrdInterface interface {
	Create(*v1.Democrd) (*v1.Democrd, error)
	Update(*v1.Democrd) (*v1.Democrd, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.Democrd, error)
	List(opts metav1.ListOptions) (*v1.DemocrdList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Democrd, err error)
	DemocrdExpansion
}

// democrds implements DemocrdInterface
type democrds struct {
	client rest.Interface
	ns     string
}

// newDemocrds returns a Democrds
func newDemocrds(c *DemocrdV1Client, namespace string) *democrds {
	return &democrds{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the democrd, and returns the corresponding democrd object, and an error if there is any.
func (c *democrds) Get(name string, options metav1.GetOptions) (result *v1.Democrd, err error) {
	result = &v1.Democrd{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("democrds").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Democrds that match those selectors.
func (c *democrds) List(opts metav1.ListOptions) (result *v1.DemocrdList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.DemocrdList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("democrds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested democrds.
func (c *democrds) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("democrds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a democrd and creates it.  Returns the server's representation of the democrd, and an error, if there is any.
func (c *democrds) Create(democrd *v1.Democrd) (result *v1.Democrd, err error) {
	result = &v1.Democrd{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("democrds").
		Body(democrd).
		Do().
		Into(result)
	return
}

// Update takes the representation of a democrd and updates it. Returns the server's representation of the democrd, and an error, if there is any.
func (c *democrds) Update(democrd *v1.Democrd) (result *v1.Democrd, err error) {
	result = &v1.Democrd{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("democrds").
		Name(democrd.Name).
		Body(democrd).
		Do().
		Into(result)
	return
}

// Delete takes name of the democrd and deletes it. Returns an error if one occurs.
func (c *democrds) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("democrds").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *democrds) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("democrds").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched democrd.
func (c *democrds) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Democrd, err error) {
	result = &v1.Democrd{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("democrds").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
